/**
 * A repo's own tooling exclusions, read from `pyproject.toml`.
 *
 * ## The claim
 *
 * A directory a repo excludes from its own linter *and* its own
 * type-checker is one it does not maintain. pydantic's `pydantic/v1`
 * appears in four separate exclusions — ruff `extend-exclude`, coverage
 * `omit`, **pyright** `exclude` and codespell `skip` — and is
 * regenerated by `make update-v1`. It accounts for **85 findings, 17.5%
 * of pydantic's whole report**.
 *
 * (The backlog entry says "mypy" for the third. It is `[tool.pyright]`,
 * and pydantic has no `[tool.mypy]` table at all — see
 * {@link DELIBERATELY_UNSUPPORTED} for why the difference matters.)
 *
 * ## Why this file is written defensively
 *
 * This turns a config file into a **silent-suppression mechanism**, and
 * the repo has six prior instances of apparatus that failed closed on
 * correct input. Three rules follow, none of them negotiable:
 *
 * **1. Named tables only.** Never "any key called `exclude`". airflow's
 * `pyproject.toml` carries `exclude = ["*"]` under
 * `[tool.hatch.build.targets.sdist]` at line 589 — a reader that honours
 * any `exclude` reports the entire repository as clean. The allowlist is
 * {@link TOOLING_EXCLUDE_TABLES} and it is asserted by its own test, so
 * widening it is a deliberate edit that fails an assertion first.
 *
 * **2. Exact keys, not prefixes.** airflow also has
 * `[tool.coverage.report] skip_empty = true` and `[tool.uv]
 * exclude-newer = "4 days"` — a `skip`-prefixed boolean and an
 * `exclude`-prefixed duration. Neither is a path.
 *
 * **3. When in doubt, exclude nothing.** Missing an exclusion costs
 * noise; inventing one costs silence, and silence is the failure this
 * exists to avoid. A value this reader does not fully understand is
 * dropped rather than guessed at.
 *
 * ## Why not a TOML parser
 *
 * A dependency would parse more of the format, but the risk here is not
 * *under*-reading — it is acting on something misread. This reader
 * recognises exactly the shapes the four allowlisted keys use and
 * ignores everything else, which makes "understood or ignored" a
 * property of ~80 lines rather than of a third-party grammar.
 */

/** One `(table, key)` pair this reader is willing to act on. */
export interface ToolingExcludeTable {
  table: string;
  key: string;
  /** How the value is written. `csv` is codespell's comma-joined string. */
  form: "array" | "csv";
  /** Shown to the user as the authority for a skip. */
  tool: string;
}

/**
 * The allowlist. Each entry is a tool that reads *source* and has been
 * told not to read these paths — a linter, a type-checker, a coverage
 * run, a spell-checker. Build-backend tables are deliberately absent:
 * `[tool.hatch.build]` describes what ships in a wheel, which says
 * nothing about whether the source is maintained.
 */
export const TOOLING_EXCLUDE_TABLES: readonly ToolingExcludeTable[] = [
  { table: "tool.ruff", key: "exclude", form: "array", tool: "ruff" },
  { table: "tool.ruff", key: "extend-exclude", form: "array", tool: "ruff" },
  { table: "tool.coverage.run", key: "omit", form: "array", tool: "coverage" },
  { table: "tool.pyright", key: "exclude", form: "array", tool: "pyright" },
  { table: "tool.codespell", key: "skip", form: "csv", tool: "codespell" },
];

/**
 * `[tool.mypy] exclude` is **deliberately absent**, and the reason is
 * worth keeping.
 *
 * The backlog entry that motivated this file names pydantic's four
 * exclusions as "ruff `extend-exclude`, coverage `omit`, mypy
 * `exclude`, codespell `skip`". Opening the file, the third is
 * `[tool.pyright]` — there is no `[tool.mypy]` table in pydantic's
 * `pyproject.toml` at all. That distinction is load-bearing rather than
 * pedantic: **pyright's `exclude` takes globs, mypy's takes regular
 * expressions.** airflow's entries are regexes of the form
 * `dot-star-slash node_modules dot-star` — spelled out rather than
 * quoted, because the literal contains a star-slash and would close
 * this comment. Read as globs they match nothing at best and the wrong
 * thing at worst. Supporting mypy means running a regex dialect against every
 * candidate path, which is a separate piece of work with its own
 * failure modes; mixing the two silently is precisely the misread this
 * whole file is written to avoid.
 */
export const DELIBERATELY_UNSUPPORTED = ["tool.mypy"] as const;

/**
 * How many distinct tools must exclude a path before crimes will skip
 * it.
 *
 * One tool's exclusion can be a quirk of that tool — a ruff-only entry
 * often means "this file trips one lint rule", not "nobody maintains
 * this". Agreement between independent tools is what carries the claim,
 * and it is the generalisation of the backlog's own argument that a
 * directory excluded from a repo's linter *and* its type-checker is one
 * it does not maintain.
 *
 * Measured on the corpus, this is what separates the real case from the
 * incidental ones: pydantic's `pydantic/v1` is named by ruff, coverage
 * and codespell (**3**), while mlflow's ruff-only list and drf's
 * codespell-only list corroborate at **1** and are therefore left alone.
 */
export const REQUIRED_CORROBORATION = 2;

export interface ToolingExclude {
  /** The TOML table the patterns came from, e.g. `tool.ruff`. */
  table: string;
  /** The key within it, e.g. `extend-exclude`. */
  key: string;
  /** The tool that owns the table, for the coverage warning's prose. */
  tool: string;
  /** Path patterns, exactly as written in the file. */
  patterns: string[];
}

const TABLE_HEADER = /^\s*\[([^\]]+)\]\s*$/;
const KEY_VALUE = /^\s*([A-Za-z0-9_-]+)\s*=\s*(.*)$/;

/**
 * Read the allowlisted exclusions from a `pyproject.toml`'s text.
 *
 * Returns one entry per `(table, key)` that was both allowlisted and
 * fully understood. Anything else — an unknown table, a near-miss key, a
 * value shape this does not recognise, a truncated file — yields
 * nothing for that key.
 */
export function readPyprojectExcludes(toml: string): ToolingExclude[] {
  const lines = toml.split("\n");
  const out: ToolingExclude[] = [];
  let table = "";

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? "";
    if (stripComment(line).trim() === "") continue;

    const header = TABLE_HEADER.exec(stripComment(line));
    if (header) {
      table = (header[1] ?? "").trim();
      continue;
    }
    if (table === "") continue;

    const kv = KEY_VALUE.exec(line);
    if (!kv) continue;
    const key = kv[1] ?? "";
    const spec = TOOLING_EXCLUDE_TABLES.find((t) => t.table === table && t.key === key);
    if (!spec) continue;

    const raw = (kv[2] ?? "").trim();
    const parsed = spec.form === "csv" ? parseCsvString(raw) : parseArray(raw, lines, i);
    if (parsed === null || parsed.patterns.length === 0) continue;
    if (spec.form === "array") i = parsed.lastLine;
    out.push({ table, key, tool: spec.tool, patterns: parsed.patterns });
  }

  return out;
}

interface ParsedValue {
  patterns: string[];
  lastLine: number;
}

/** `'a,b,c'` → `["a","b","c"]`. Codespell's shape, and only its shape. */
function parseCsvString(raw: string): ParsedValue | null {
  const quoted = /^(['"])(.*)\1\s*$/.exec(stripComment(raw).trim());
  if (!quoted) return null;
  const patterns = (quoted[2] ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s !== "");
  return { patterns, lastLine: -1 };
}

/**
 * `['a', 'b']`, on one line or several. Returns `null` — meaning
 * "exclude nothing" — if the array never closes, which is what a
 * truncated or malformed file looks like.
 */
function parseArray(raw: string, lines: string[], start: number): ParsedValue | null {
  if (!raw.startsWith("[")) return null;

  let buffer = "";
  let line = start;
  let depth = 0;
  let closed = false;

  for (; line < lines.length; line += 1) {
    const text = line === start ? raw : (lines[line] ?? "");
    const cleaned = stripComment(text);
    for (const ch of cleaned) {
      if (ch === "[") depth += 1;
      else if (ch === "]") {
        depth -= 1;
        if (depth === 0) closed = true;
      }
    }
    buffer += `${cleaned}\n`;
    if (closed) break;
  }
  if (!closed) return null;

  const inner = buffer.slice(buffer.indexOf("[") + 1, buffer.lastIndexOf("]"));
  const patterns: string[] = [];
  for (const item of inner.split(",")) {
    const trimmed = item.trim();
    if (trimmed === "") continue;
    const quoted = /^(['"])(.*)\1$/.exec(trimmed);
    // A non-literal entry (a variable, a nested table) means this is not
    // a shape we understand — drop the whole key rather than part of it.
    if (!quoted) return null;
    const value = quoted[2] ?? "";
    if (value !== "") patterns.push(value);
  }
  return { patterns, lastLine: line };
}

/**
 * Remove a trailing `#` comment. Quote-aware, so a `#` inside a pattern
 * survives — `'src/#weird'` is a legal path.
 */
function stripComment(line: string): string {
  let quote: string | null = null;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (quote) {
      if (ch === quote) quote = null;
    } else if (ch === "'" || ch === '"') {
      quote = ch;
    } else if (ch === "#") {
      return line.slice(0, i);
    }
  }
  return line;
}

/** A path the repo's own tooling excludes, and who said so. */
export interface CorroboratedExclude {
  /** The pattern, normalised to a directory-or-glob crimes can match. */
  pattern: string;
  /** Distinct tools naming it, sorted. Length >= REQUIRED_CORROBORATION. */
  tools: string[];
  /** `table.key` for each, so a warning can cite the exact lines. */
  authorities: string[];
}

/**
 * Reduce a pattern to the thing two tools can be said to agree *about*.
 *
 * `pydantic/v1`, `pydantic/v1/*` and `pydantic/v1/**` are three
 * spellings of one directory, and without this they corroborate at 1
 * each instead of 3. Trailing globs and slashes come off; everything
 * else is left exactly as written, because inventing a broader pattern
 * than the repo did is the failure mode that matters.
 */
export function normaliseExcludePattern(pattern: string): string {
  return pattern
    .replace(/\/+\*{1,2}$/, "")
    .replace(/\/+$/, "")
    .trim();
}

/**
 * Group the raw entries by normalised path and keep only those named by
 * at least {@link REQUIRED_CORROBORATION} distinct tools.
 *
 * Two keys of the *same* tool — ruff's `exclude` and `extend-exclude` —
 * count once. Corroboration means independent tools, not independent
 * lines.
 */
export function corroborate(
  entries: readonly ToolingExclude[],
  required: number = REQUIRED_CORROBORATION,
): CorroboratedExclude[] {
  const byPattern = new Map<string, { tools: Set<string>; authorities: Set<string> }>();
  for (const entry of entries) {
    for (const raw of entry.patterns) {
      const pattern = normaliseExcludePattern(raw);
      if (pattern === "" || pattern === "*" || pattern === "**") continue;
      const bucket = byPattern.get(pattern) ?? {
        tools: new Set<string>(),
        authorities: new Set<string>(),
      };
      bucket.tools.add(entry.tool);
      bucket.authorities.add(`${entry.table}.${entry.key}`);
      byPattern.set(pattern, bucket);
    }
  }

  const out: CorroboratedExclude[] = [];
  for (const [pattern, { tools, authorities }] of byPattern) {
    if (tools.size < required) continue;
    out.push({
      pattern,
      tools: [...tools].sort(),
      authorities: [...authorities].sort(),
    });
  }
  return out.sort((a, b) => a.pattern.localeCompare(b.pattern));
}
