import { AGENT_SKILL_TEXT, SKILL_VERSION, skillHash } from "./template.js";

// Exact generated bytes from the published npm packages, before management
// metadata existed. Unknown/customized legacy text always needs review.
const LEGACY_SKILLS = new Map([
  ["4cda4856d1cce5b5abde69cd93cee032ab00138c286229d514fec61b05392a4a", "0.27.0"],
  ["a7f296b9ca5caa8ea9d9dc0f4ab9f6f572220b474e219b3e666d9195e4efd979", "0.28.0"],
]);

export interface SkillState {
  status: "missing" | "current" | "outdated" | "customized" | "newer";
  version?: string;
}

export function inspectSkill(text: string | undefined): SkillState {
  if (text === undefined) return { status: "missing" };
  text = text.replaceAll("\r\n", "\n");
  if (text === AGENT_SKILL_TEXT) return { status: "current", version: SKILL_VERSION };
  const legacy = LEGACY_SKILLS.get(skillHash(text));
  if (legacy) return { status: "outdated", version: legacy };
  const marker = /\n<!-- crimes-skill (\{[^\n]+\}) -->\n$/.exec(text);
  if (!marker) return { status: "customized" };
  let meta: { format?: unknown; version?: unknown; sha256?: unknown };
  try {
    meta = JSON.parse(marker[1]!);
  } catch {
    return { status: "customized" };
  }
  if (
    meta === null ||
    typeof meta !== "object" ||
    meta.format !== 1 ||
    typeof meta.version !== "string" ||
    !/^\d+\.\d+\.\d+$/.test(meta.version) ||
    meta.sha256 !== skillHash(text.slice(0, marker.index))
  ) {
    return { status: "customized" };
  }
  const installed = meta.version.split(".").map(Number);
  const current = SKILL_VERSION.split(".").map(Number);
  const difference = installed.map((n, i) => n - current[i]!).find((n) => n !== 0);
  return {
    status: difference !== undefined && difference > 0 ? "newer" : "outdated",
    version: meta.version,
  };
}

/** A single trimmed unified hunk; no git executable or diff dependency needed. */
export function skillDiff(path: string, before: string, after: string): string {
  const oldLines = before.length === 0 ? [] : before.trimEnd().split("\n");
  const newLines = after.length === 0 ? [] : after.trimEnd().split("\n");
  let start = 0;
  while (start < oldLines.length && oldLines[start] === newLines[start]) start++;
  let end = 0;
  while (
    end < oldLines.length - start &&
    end < newLines.length - start &&
    oldLines[oldLines.length - end - 1] === newLines[newLines.length - end - 1]
  )
    end++;
  const contextStart = Math.max(0, start - 3);
  const contextEnd = Math.min(end, 3);
  const lines = [
    `--- ${path} (installed)`,
    `+++ ${path} (crimes ${SKILL_VERSION})`,
    `@@ -${contextStart + 1},${oldLines.length - end + contextEnd - contextStart} +${contextStart + 1},${newLines.length - end + contextEnd - contextStart} @@`,
    ...oldLines.slice(contextStart, start).map((line) => ` ${line}`),
    ...oldLines.slice(start, oldLines.length - end).map((line) => `-${line}`),
    ...newLines.slice(start, newLines.length - end).map((line) => `+${line}`),
    ...oldLines
      .slice(oldLines.length - end, oldLines.length - end + contextEnd)
      .map((line) => ` ${line}`),
  ];
  return lines.join("\n") + "\n";
}
